apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterpilot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clusterpilot
  template:
    metadata:
      labels:
        app: clusterpilot
    spec:
      containers:
        - name: clusterpilot
          image: clusterpilot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000